### ISSUE TITLE
Something that puzzles me in the code

### ISSUE THREAD

**Issue by jueliangguke** [AMLab-Amsterdam/MNF_VBNN#1]
My puzzle is mainly in dense_layers.py

1. In line 40 and 41, in my opinion, the mean and variance of q(z_0) are defined respectively. But why the names contain 'dropout_rates', maybe I am wrong?
https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/c24c256ca7cae88216013924dac5087db8f24730/dense_layers.py#L40
https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/c24c256ca7cae88216013924dac5087db8f24730/dense_layers.py#L41

2. It seems that line 110 is to compute q(z_0), for equation (16) in paper.
https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/c24c256ca7cae88216013924dac5087db8f24730/dense_layers.py#L110
I think the z_0 is sampled from q(z_0) in line 74:
https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/c24c256ca7cae88216013924dac5087db8f24730/dense_layers.py#L74
But in line 110 variable logqm is independent from sample_M, why?

3. In line 127, \widetilde{\sigma}_i  is computed, for equation (10) in paper, but a sigmoid non-linearity is not used as (10). As it is not important?
https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/c24c256ca7cae88216013924dac5087db8f24730/dense_layers.py#L127

**Comment by clouizos** [comment]
Hey there, 

Let me address your questions:

1. Yes these lines define the mean and variance of the multiplicative noise variable z; due to similarities with Gaussian dropout the naming of the tensorflow variables adopted the droprates convention.

2. The naming here indeed can be a bit confusing; in line 110 we compute the entropy of the initial distribution q(z_0) which is independent of the actual sample z_0.

3. Ah indeed, in the code it is slightly different as wv__ computes the log of the variance of r(z|W), as that is more numerically stable. The paper hasn't been updated to reflect that change.

Hope this helps!
