### ISSUE TITLE
Questions/possible errors

### ISSUE THREAD

**Issue by janosh** [AMLab-Amsterdam/MNF_VBNN#4]
Is there a `tanh` missing on lines [137 and 140](https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/37b060e8264b3b738fb59f6510d3bdee8f164865/conv_layers.py#L137) of `conv_layers.py`?

```diff
- a = mw + tf.sqrt(vw) * eps
+ a = tf.tanh(mw + tf.sqrt(vw) * eps)
...
- a += mb + tf.sqrt(vb) * tf.random_normal(())
+ a += tf.tanh(mb + tf.sqrt(vb) * tf.random_normal(()))
```

Similarly, how come we don't add the bias contribution to the shared network output `a` after [line 123](https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/37b060e8264b3b738fb59f6510d3bdee8f164865/dense_layers.py#L123) in `dense_layers.py`?

Also, does the `kldiv` method as you defined it return the negative KL divergence? It seems to be used correctly in the end though, since it's negated again in [`get_reg()`](https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/37b060e8264b3b738fb59f6510d3bdee8f164865/layers.py#L36).

**Comment by clouizos** [comment]
Hi 

Apologies for the late reply, I am not at the university any more and I don't check this repo. We found out that for convolutional layers, linear mappings worked better hence we didn't add the tanh. The bias contribution is not added for dense layers since the multiplicative noise is at the input units (hence it doesn't affect the biases), and yes you are correct, the kldiv is returning the negative kl-divergence (which indeed can be confusing and should be changed...). 

I hope this helped! I will be closing this issue and the issue tracker as this code is provided as is and is not maintained any more.
